name: Ledger CI

on:
  pull_request:
    branches: [ main ]

jobs:
  validate-ledger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Run ledger validation
        run: make ledger-ci
